---
- name: Configure Hosts File
  hosts: elasticstack
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Update the /etc/hosts file with node name
    become: yes
    become_user: root
    lineinfile:
        path: "/etc/hosts"
        regexp: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['inventory_hostname']}}"
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['inventory_hostname']}}"
        state: present
        backup: yes
    register: etchostsupdate
    when: ansible_hostname != item or ansible_hostname == item
    with_items: "{{groups['elasticstack']}}"

- name: Configure Elasticsearch Nodes
  hosts: elasticnodes
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: common
  - role: elasticsearch

- name: Install Kibana Server
  hosts: kibana
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: common
  - role: kibana

- name: Configure Filebeat Test Nodes
  hosts: testnodes
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: common
  - role: filebeats
