---
- name: Install Elasticsearch & Kibana Single Node Server
  hosts: elksingle
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: common
    when: ansible_distribution == 'CentOS' and (ansible_distribution_version == '6.4' or ansible_distribution_version == '7.7') or ansible_distribution == 'Ubuntu' and (ansible_distribution_version == '18.04' or ansible_distribution_version == '20.04')
  - role: elknode
    when: ansible_distribution == 'CentOS' and (ansible_distribution_version == '6.4' or ansible_distribution_version == '7.7') or ansible_distribution == 'Ubuntu' and (ansible_distribution_version == '18.04' or ansible_distribution_version == '20.04')

