---
- name: Install Dev Tools |  'Development tools' package group
  yum:
    name: "@Development tools"


- name: Install | Base packages
  yum:
    name:
      - git 
      - vim
      - wget   

- name: Install | JAVA Packages
  yum:
    name:
      - java-11-openjdk-devel
      - java-11-openjdk

- name: Be sure firewalld is disabled
  systemd: 
    name: firewalld 
    enabled: no
  ignore_errors: yes

- name: Be sure firewalld is stopped
  systemd: 
    name: firewalld 
    state: stopped
  ignore_errors: yes

- name: Disable Selinux
  selinux:
    policy: targeted
    state: disabled
  ignore_errors: yes

