modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET

  ping_node:
    prober: icmp
    timeout: 3s
    icmp:
      preferred_ip_protocol: "ip4"
