---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  become: true

- name: Add Git Repository 
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa

- name: Installing Dependencies
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - python-pip
      - python-apt 
      - openjdk-8-jdk
      - libfontconfig
      - libffi-dev
      - libncurses5-dev
  become: true

- name: Installing Other Package Dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - gnupg2
      - git-core
      - zlib1g-dev 
      - build-essential 
      - libssl-dev 
      - libreadline-dev 
      - libyaml-dev 
      - libsqlite3-dev 
      - sqlite3 
      - libxml2-dev 
      - libxslt1-dev 
      - libcurl4-openssl-dev 
      - software-properties-common 
      - libffi-dev 
      - nodejs 
      - yarn
      - libffi-dev
      - libncurses5-dev
      - unzip
  become: true
