---
- import_playbook: poc-setup.yml

- name: Hosts File Update | Configure POC Servers
  hosts: pocservers
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Update the /etc/hosts file with node name
    become: yes
    become_user: root
    lineinfile:
        path: "/etc/hosts"
        regexp: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['inventory_hostname']}}"
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['inventory_hostname']}}"
        state: present
        backup: yes
    register: etchostsupdate
    when: ansible_hostname != item or ansible_hostname == item
    with_items: "{{groups['pocservers']}}"
