# Install Blackbox Exporter
- name: Download | Blackbox Exporter
  unarchive:
    src: "{{ blackbox_exporter_url }}"
    dest: "/tmp/"
    remote_src: yes
  become: True

- name: Copy | Node Blackbox Exporter Executables
  copy:
    src: "/tmp/{{ blackbox_exporter_extract_folder }}/blackbox_exporter"
    dest: "/usr/local/bin/"
    mode: 0755
    remote_src: true
  become: true 

- name: Create | Blackbox Folder
  file:
      path: "{{ blackbox_etc_dir }}"
      state: directory
      mode: 0755
      owner: "{{ prom_user }}"
      group: "{{ prom_user }}"
  become: true


- name: Copy | Blackbox Exporter Config
  copy:
    src: "blackbox.yml"
    dest: "/etc/blackbox_exporter/blackbox.yml"
  become: true


- name: Copy | Blackbox Exporter Service
  copy:
    src: "blackbox_exporter.service"
    dest: "/etc/systemd/system/"
  become: true

- name: Reload
  shell: sudo systemctl daemon-reload
  become: true

- name: Service | Enable Blackbox Exporter
  systemd:
    name: blackbox_exporter
    enabled: yes
    state: restarted
