---
- name: Filebeat | Install Filebeat
  yum:
     name: "{{ filebeat_rpm_url }}"
     state: present
  when:
  - ansible_os_family == 'RedHat'

- name: Filebeat | Install Filebeat
  apt:
     deb: "{{ filebeat_deb_url }}"
     state: present
  when:
  - ansible_os_family == 'Debian'

- name: Filebeat | Enable filebeat service
  systemd:
     name: filebeat
     state: started
     enabled: yes

- name: Filebeat | Update filebeat config
  template:
    src: "filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
  register: filebeat_service

- name: Filebeat | Restart filebeat if config changes
  systemd:
     name: filebeat
     state: restarted
     daemon_reload: yes
  when: filebeat_service.changed
