---
- name: Kibana | Install Kibana
  yum:
     name: "{{ kibana_url }}"
     state: present

- name: Elasticsearch | Install elasticsearch
  yum:
     name: "{{ elasticsearch_url }}"
     state: present


- name: Elasticsearch | Update elasticsearch config
  template:
    src="elasticsearch.yml.erb"
    dest="/etc/elasticsearch/elasticsearch.yml"
  register: elasticsearch_service

- name: Elasticsearch | Update jvm config
  copy:
    src: "jvm.options"
    dest: "/etc/elasticsearch/jvm.options"
  register: elasticsearch_service_jvm

- name: Kibana | Update kibana config
  template:
    src="kibana.yml.erb"
    dest="/etc/kibana/kibana.yml"
  register: kibana_service


- name: Elasticsearch | Restart elasticsearch
  systemd:
     name: elasticsearch
     state: restarted
     daemon_reload: yes
  when: elasticsearch_service.changed


- name: Kibana | Restart kibana
  systemd:
     name: kibana
     state: restarted
     daemon_reload: yes
  when: kibana_service.changed
