# Install Alert Manager
- name: Download | Node Alert manager
  unarchive:
    src: "{{ alertmanager_url }}"
    dest: "/tmp/"
    remote_src: yes
  become: True

- name: Copy | Alert Manager Executable
  copy:
    src: "/tmp/{{ alertmanager_extract_folder }}/alertmanager"
    dest: "/usr/local/bin/"
    mode: 0755
    remote_src: true
  become: true 

- name: Copy | Alert Manager amtool
  copy:
    src: "/tmp/{{ alertmanager_extract_folder }}/amtool"
    dest: "/usr/local/bin/"
    mode: 0755
    remote_src: true
  become: true

- name: Create | Alert Manager Folder
  file:
      path: "{{ alertmanager_etc_dir }}"
      state: directory
      mode: 0755
      owner: "{{ prom_user }}"
      group: "{{ prom_user }}"
  become: true

- name: Create | Alert Manager Data Folder
  file:
      path: "{{ alertmanager_data_dir }}"
      state: directory
      mode: 0755
      owner: "{{ prom_user }}"
      group: "{{ prom_user }}"
  become: true

- name: Copy | Alertmanager etc config
  template:
    src: "alertmanager.yml.j2"
    dest: "{{ alertmanager_etc_dir }}/alertmanager.yml"
  become: true


- name: Copy | Alert Manager Service
  copy:
    src: "alertmanager.service"
    dest: "/etc/systemd/system/"
  become: true

- name: Reload
  shell: sudo systemctl daemon-reload
  become: true


- name: Service | Enable Alert Manager Service
  systemd:
    name: alertmanager
    enabled: yes
    state: restarted
  become: true
