---
- name: Install Kibana Server
  hosts: kibana
  become: yes
  become_user: root
  become_method: sudo
  remote_user: ec2-user
  roles:
  - role: RHEL7-Common/common
  - role: elastic-7.7/jdk
  - role: elastic-7.7/kibana  
