---
- name: Configure Prometheus Nodes
  hosts: prom_nodes
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: prometheus/user
  #- role: prometheus/system
  - role: prometheus/prometheus_nodes-install
