---
ansible_connection: ssh
ansible_user: ubuntu
ansible_python_interpreter: 'python3'

prom_user: "prometheus"
etc_conf_dir: "/etc/prometheus"
var_conf_dir: "/var/lib/prometheus"
prometheus_version: "2.27.1"
prometheus_extract_folder : "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
node_exporter_version: "1.1.2"
node_exporter_extract_folder: "node_exporter-{{ node_exporter_version }}.linux-amd64"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

alertmanager_version: "0.22.2"
alertmanager_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
alertmanager_extract_folder: "alertmanager-{{ alertmanager_version }}.linux-amd64"
alertmanager_etc_dir: "/etc/alertmanager"
alertmanager_data_dir: "/data"

blackbox_version: "0.19.0"
blackbox_exporter_url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_version }}/blackbox_exporter-{{ blackbox_version }}.linux-amd64.tar.gz"
blackbox_exporter_extract_folder: "blackbox_exporter-{{ blackbox_version }}.linux-amd64"
blackbox_etc_dir: "/etc/blackbox_exporter"
blackbox_data_dir: "/data"

prometheus_user:
  - username: prometheus
    user_group: prometheus
    gekos: "Prometheus User"
    user_home: "/home/prometheus"
    user_shell: "/bin/bash"
    use_sudo: true
    user_groups: "prometheus"


prometheus_node_targets: ['prom-node1:9100','prom-node2:9100']
